[package]
name = "rust-joiner-xls"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
calamine = "0.18.0"
clap = "2.33.3"
chrono = "0.4.19"

[dependencies.zip]
version = "0.5.5"